version: 1.0.{build}-{branch}

skip_tags: true
clone_depth: 1

image:
  - Visual Studio 2013
  - Visual Studio 2015

configuration:
  - Debug
  - Release

platform:
  - Win32
  - X64

build:
  parallel: true
  verbosity: normal

test_script:
- ps: >-
    vstest.console /logger:Appveyor .\$(CONFIGURATION)\Engine_Graphics_Test.dll

    vstest.console /logger:Appveyor .\$(CONFIGURATION)\Engine_Graphics_IO.dll

    vstest.console /logger:Appveyor .\$(CONFIGURATION)\Engine_Graphics_Maths.dll
